apiVersion: apps/v1
kind: Deployment
metadata:
  name: radstream-triton
  namespace: radstream
  labels:
    app: radstream-triton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radstream-triton
  template:
    metadata:
      labels:
        app: radstream-triton
    spec:
      containers:
      - name: triton-server
        image: radstream-triton:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: 1
        env:
        - name: TRITON_MODEL_STORE
          value: "/models"
        - name: TRITON_SERVER_HTTP_PORT
          value: "8000"
        - name: TRITON_SERVER_GRPC_PORT
          value: "8001"
        - name: TRITON_SERVER_METRICS_PORT
          value: "8002"
        livenessProbe:
          httpGet:
            path: /v2/health/ready
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v2/health/ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: model-storage
          mountPath: /models
      volumes:
      - name: model-storage
        emptyDir: {}
      nodeSelector:
        accelerator: nvidia-tesla-t4
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: radstream-triton-service
  namespace: radstream
  labels:
    app: radstream-triton
spec:
  selector:
    app: radstream-triton
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: grpc
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: metrics
    port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: radstream-triton-hpa
  namespace: radstream
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: radstream-triton
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
